project_id = "atvrtfwbixjfvovvdguk"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-webhook]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.email-hook]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
